version: '3.7'

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_ROOT_PASSWORD: Clarusway_1
    networks:
      - webnet

  websrv:
    restart: always
    depends_on:
      - database
    build: .
    networks:
      - webnet
    ports:
      - "80:5000"
networks:
  webnet:
    driver: bridge