apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name:  demo
          image: sahinturk57/flask:project
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: MYSQL_DATABASE_HOST
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: MYSQL_USER
